const BlogApi = [
    {
        id: 1,
        image: "./image/blog-01.jpg",
        date: "2 May, 2021",
        title_one: "Digital Marketo to Their New Office.",
        desc_one: "Nobis Nulla non ligula vel Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas aspernatur omnis suscipit repudiandae aliquid provident ipsum delectus, ipsam beatae autem magnam porro eos velit! Commodi et error laudantium dolor minima? nisi blandit egestas vel eget leo. Praesent f Nulla non ligula vel nisi blandit egestas vel eget leo. Praesent.Nulla non ligula vel Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas aspernatur omnis suscipit repudiandae aliquid provident ipsum delectus, ipsam beatae autem magnam porro eos velit! Commodi et error laudantium dolor minima? nisi blandit egestas vel eget leo. Praesent f Nulla non ligula vel nisi blandit egestas vel eget leo. Praesent. eleifend option congue nihil imperdiet doming id quod mazim p Nulla non ligula vel nisi blandit egestas vel eget leo. Praesent. ",
        title_two: "Nobis eleifend option conguenes.",
        desc_two: "Mauris tempor, orci Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas aspernatur omnis suscipit repudiandae aliquid provident ipsum delectus, ipsam beatae autem magnam porro eos velit! Commodi et error laudantium dolor minima? id pellentesque convallis, massa mi congue eros,",
        title_three: "Mauris tempor, orci id pellentesque.",
        desc_three: "Nulla non ligula vel Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas aspernatur omnis suscipit repudiandae aliquid provident ipsum delectus, ipsam beatae autem magnam porro eos velit! Commodi et error laudantium dolor minima? nisi blandit egestas vel eget leo. Praesent f Nulla non ligula vel nisi blandit egestas vel eget leo. Praesent.",
    },
    {
        id: 2,
        image: "./image/blog-02.jpg",
        date: "28 April, 2021",
        title_one: "The services provide for design",
        desc_one: "Nobis Nulla non ligula vel Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas aspernatur omnis suscipit repudiandae aliquid provident ipsum delectus, ipsam beatae autem magnam porro eos velit! Commodi et error laudantium dolor minima? nisi blandit egestas vel eget leo. Praesent f Nulla non ligula vel nisi blandit egestas vel eget leo. Praesent.Nulla non ligula vel Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas aspernatur omnis suscipit repudiandae aliquid provident ipsum delectus, ipsam beatae autem magnam porro eos velit! Commodi et error laudantium dolor minima? nisi blandit egestas vel eget leo. Praesent f Nulla non ligula vel nisi blandit egestas vel eget leo. Praesent. eleifend option congue nihil imperdiet doming id quod mazim p Nulla non ligula vel nisi blandit egestas vel eget leo. Praesent. ",
        title_two: "Nobis eleifend option conguenes.",
        desc_two: "Mauris tempor, orci id pellentesque convallis, massa mi congue eros,",
        title_three: "Mauris tempor, orci id pellentesque.",
        desc_three: "Nulla non ligula vel Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas aspernatur omnis suscipit repudiandae aliquid provident ipsum delectus, ipsam beatae autem magnam porro eos velit! Commodi et error laudantium dolor minima?nisi blandit egestas vel eget leo. Praesent f Nulla non ligula vel nisi blandit egestas vel eget leo. Praesent.",
    },
    {
        id: 3,
        image: "./image/blog-03.jpg",
        date: "2 May, 2021",
        title_one: "Digital Marketo to Their New Office.",
        desc_one: "Nobis Nulla non ligula vel Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas aspernatur omnis suscipit repudiandae aliquid provident ipsum delectus, ipsam beatae autem magnam porro eos velit! Commodi et error laudantium dolor minima? nisi blandit egestas vel eget leo. Praesent f Nulla non ligula vel nisi blandit egestas vel eget leo. Praesent.Nulla non ligula vel Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas aspernatur omnis suscipit repudiandae aliquid provident ipsum delectus, ipsam beatae autem magnam porro eos velit! Commodi et error laudantium dolor minima? nisi blandit egestas vel eget leo. Praesent f Nulla non ligula vel nisi blandit egestas vel eget leo. Praesent. eleifend option congue nihil imperdiet doming id quod mazim p Nulla non ligula vel nisi blandit egestas vel eget leo. Praesent. ",
        title_two: "Nobis eleifend option conguenes.",
        desc_two: "Mauris tempor, orci id pellentesque convallis, massa mi congue eros,",
        title_three: "Mauris tempor, orci id pellentesque.",
        desc_three: "Nulla non ligula velLorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas aspernatur omnis suscipit repudiandae aliquid provident ipsum delectus, ipsam beatae autem magnam porro eos velit! Commodi et error laudantium dolor minima? nisi blandit egestas vel eget leo. Praesent f Nulla non ligula vel nisi blandit egestas vel eget leo. Praesent.",
    },
    {
        id: 4,
        image: "./image/blog-04.jpg",
        date: "28 April, 2021",
        title_one: "The services provide for design",
        desc_one: "Nobis Nulla non ligula vel Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas aspernatur omnis suscipit repudiandae aliquid provident ipsum delectus, ipsam beatae autem magnam porro eos velit! Commodi et error laudantium dolor minima? nisi blandit egestas vel eget leo. Praesent f Nulla non ligula vel nisi blandit egestas vel eget leo. Praesent.Nulla non ligula vel Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas aspernatur omnis suscipit repudiandae aliquid provident ipsum delectus, ipsam beatae autem magnam porro eos velit! Commodi et error laudantium dolor minima? nisi blandit egestas vel eget leo. Praesent f Nulla non ligula vel nisi blandit egestas vel eget leo. Praesent. eleifend option congue nihil imperdiet doming id quod mazim p Nulla non ligula vel nisi blandit egestas vel eget leo. Praesent. ",
        title_two: "Nobis eleifend option conguenes.",
        desc_two: "Mauris tempor, orci id pellentesque convallis, massa mi congue eros,",
        title_three: "Mauris tempor, orci id pellentesque.",
        desc_three: "Nulla non ligula vel Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas aspernatur omnis suscipit repudiandae aliquid provident ipsum delectus, ipsam beatae autem magnam porro eos velit! Commodi et error laudantium dolor minima?nisi blandit egestas vel eget leo. Praesent f Nulla non ligula vel nisi blandit egestas vel eget leo. Praesent.",
    },
    {
        id: 5,
        image: "./image/blog-05.jpg",
        date: "2 May, 2021",
        title_one: "Digital Marketo to Their New Office.",
        desc_one: "Nobis Nulla non ligula vel Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas aspernatur omnis suscipit repudiandae aliquid provident ipsum delectus, ipsam beatae autem magnam porro eos velit! Commodi et error laudantium dolor minima? nisi blandit egestas vel eget leo. Praesent f Nulla non ligula vel nisi blandit egestas vel eget leo. Praesent.Nulla non ligula vel Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas aspernatur omnis suscipit repudiandae aliquid provident ipsum delectus, ipsam beatae autem magnam porro eos velit! Commodi et error laudantium dolor minima? nisi blandit egestas vel eget leo. Praesent f Nulla non ligula vel nisi blandit egestas vel eget leo. Praesent. eleifend option congue nihil imperdiet doming id quod mazim p Nulla non ligula vel nisi blandit egestas vel eget leo. Praesent. ",
        title_two: "Nobis eleifend option conguenes.",
        desc_two: "Mauris tempor, orci id pellentesque convallis, massa mi congue eros,",
        title_three: "Mauris tempor, orci id pellentesque.",
        desc_three: "Nulla non ligula vel Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas aspernatur omnis suscipit repudiandae aliquid provident ipsum delectus, ipsam beatae autem magnam porro eos velit! Commodi et error laudantium dolor minima? nisi blandit egestas vel eget leo. Praesent f Nulla non ligula vel nisi blandit egestas vel eget leo. Praesent.",
    },
    {
        id: 6,
        image: "./image/blog-06.jpg",
        date: "28 April, 2021",
        title_one: "The services provide for design",
        desc_one: "Nobis Nulla non ligula vel Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas aspernatur omnis suscipit repudiandae aliquid provident ipsum delectus, ipsam beatae autem magnam porro eos velit! Commodi et error laudantium dolor minima? nisi blandit egestas vel eget leo. Praesent f Nulla non ligula vel nisi blandit egestas vel eget leo. Praesent.Nulla non ligula vel Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas aspernatur omnis suscipit repudiandae aliquid provident ipsum delectus, ipsam beatae autem magnam porro eos velit! Commodi et error laudantium dolor minima? nisi blandit egestas vel eget leo. Praesent f Nulla non ligula vel nisi blandit egestas vel eget leo. Praesent. eleifend option congue nihil imperdiet doming id quod mazim p Nulla non ligula vel nisi blandit egestas vel eget leo. Praesent. ",
        title_two: "Nobis eleifend option conguenes.",
        desc_two: "Mauris tempor, orci id pellentesque convallis, massa mi congue eros,",
        title_three: "Mauris tempor, orci id pellentesque.",
        desc_three: "Nulla non ligula vel nisi blandit Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas aspernatur omnis suscipit repudiandae aliquid provident ipsum delectus, ipsam beatae autem magnam porro eos velit! Commodi et error laudantium dolor minima? egestas vel eget leo. Praesent f Nulla non ligula vel nisi blandit egestas vel eget leo. Praesent.",
    }]

export default BlogApi